# Create your compose file. To learn more, please visit
# https://docs.docker.com/reference/compose-file/
services:
  ollama:
    image: ollama/ollama:0.10.1
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

networks:
  default:
    name: agentic-rag

volumes:
  ollama:
